language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: EyAWjiGamhbSFGXL4IDXp70GuQB136+B5WXyXv4KlGqCih+hWpz7xuu7QSLJOKISQLu5tZtolFYpff0JZwnuBYSLp1TbQ91vJupGzPIHl/yM9seOohU5UVxH2Zo+ra2hUlvvacA1EahUAFjLyrfQRa3DWvlBhCQf8jOGSqIg6aqJVNb1EWBGSEOD25AYyDBc0l5v18eF2gYa5BbvbETaWC8QvX0OidM4aSwCrgoDJ1euvz1BZ7scGZjCu9UPYwbIz2jH52xNgieuAP12KOgQkIzg2FqEGzbzoaRGDDd53eQKYIHP3lUh1Ndojx4PH97XzN7ODYrPxiImqm08HUTE80vhkYSysj8GX75QdrXUzH0pX5L2aybL8cwZqHxTK8huq3U+m96KDuQcIW94fOCZ/Tb2MZFWF6D4PTadiQqBMGAgMvpY5DxJfKOLAmVQGg6pY64DNLHD41En+I9i5FpHVzykrgznfcEAiCAN0srXdJkYCVIqm+OLv9VGpYwaw9xgclcj7IuATvGQ+7f72NAB6iREbvJ5Kc2mw9j6sZaUlC6C1zYwX3ba4ShsQc7DxyD+w2gOGKkRiT1qpirOFQFVdBd1HnCYPozJogzdUXloMpWUTY8Usmq1LnrEB5PbXDUxraiUaiPPxBkT3AjOoIPzea6UpuD0Aa4n5lImzgabUkQ=
  app: tranquility-now
  on:
    repo: dermio/tranquility-now
