name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.9.9 # This is the deploy action
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "tranquility-now" # Must be unique in Heroku
          heroku_email: "flcpge@yahoo.com"
        env:
          HD_DATABASE_URL: ${{ secrets.DATABASE_URL }} # Heroku config vars
